server:
  port: 7777

app:
  angular: "http://localhost:4200"
  api: "http://localhost:8080"
  wavefront: "http://localhost:9411"

management:
  wavefront:
    uri: proxy://localhost:2878
    application:
      name: vere-copia
      service-name: store-gateway 
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true

---
spring:
  config:
    activate:
      on-cloud-platform: kubernetes

server:
  port: 8080

management:
  wavefront:
    uri: proxy://wavefront-proxy:2878

app:
  angular: "http://store-kiosk"
  api: "http://store-operations"
  wavefront: "http://wavefront-proxy:9411"