server:
  port: 8080

central_inventory:
  url: "http://localhost:8082"

spring:
  application:
    name: "store-operations"
  datasource:
    url: "jdbc:postgresql://127.0.0.1:25432/store_operations"
    username: postgres
    password: password
    hikari:
      connection-timeout: 10000
  jpa:
    open-in-view: false
  flyway:
    baseline-on-migrate: true
    table: store-operations-schema-version

management:
  wavefront:
    uri: proxy://localhost:2878
    application:
      name: vere-copia
      service-name: store-opertions   
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true

---
spring:
  config:
    activate:
      on-cloud-platform: kubernetes


management:
  wavefront:
    uri: proxy://wavefront-proxy:2878

central_inventory:
  url: "http://central-inventory"