apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: vere-copia-pg
spec:
  instances: 3

  # Example of rolling update strategy:
  # - unsupervised: automated update of the primary once all
  #                 replicas have been upgraded (default)
  # - supervised: requires manual supervision to perform
  #               the switchover of the primary
  primaryUpdateStrategy: unsupervised

  # Require 1Gi of space
  storage:
    size: 1Gi

  # Pin version of postgres to 13.6    
  imageName: ghcr.io/cloudnative-pg/postgresql:13.6