
server:
  port: 8082

spring:
  application:
    name: "central-inventory"
  datasource:
    url: "jdbc:postgresql://127.0.0.1:25432/central_inventory"
    username: postgres
    password: password
  jpa:
    open-in-view: false

management:
  metrics:
    export:
      wavefront:
        uri: "proxy://localhost:2878"
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

# wavefront
wavefront:
  application:
    name: vere-copia
    service: central-inventory
  freemium-account: false
