server:
  port: 8082

spring:
  application:
    name: "central-inventory"
  datasource:
    url: "jdbc:postgresql://127.0.0.1:25432/central_inventory"
    username: postgres
    password: password
    hikari:
      connection-timeout: 10000
  jpa:
    open-in-view: false
  flyway:
    baseline-on-migrate: true
    table: central-inventory-schema-version

management:
  wavefront:
    uri: proxy://localhost:2878
    application:
      name: vere-copia
      service-name: central-inventory
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
---
spring:
  config:
    activate:
      on-cloud-platform: kubernetes

server:
  port: 8080

management:
  wavefront:
    uri: proxy://wavefront-proxy:2878
