version: '3.7'

volumes:
  postgres:
  pgadmin:

services:
  wavefrontProxy:
    container_name: verecopia_wavefront_proxy
    image: wavefronthq/proxy:latest
    env_file:
      - ".env"
    environment:
      WAVEFRONT_TOKEN: ${WAVEFRONT_TOKEN}
      WAVEFRONT_URL:  "https://longboard.wavefront.com/api/"
      WAVEFRONT_PROXY_ARGS: "--traceZipkinListenerPorts 9411"
      JAVA_HEAP_USAGE: "512m"
    ports:
    - "2878:2878"
    - "9411:9411"
  postgres:
    container_name: verecopia_postgres
    image: "postgres:12"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
      PGDATA: "/data/postgres"
    volumes:
      - postgres:/data/postgres
      - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
    ports:
      - "25432:5432"
    restart: unless-stopped
  pgadmin:
    container_name: verecopia_pgadmin
    image: "dpage/pgadmin4:6.10"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
    volumes:
      - pgadmin:/var/lib/pgadmin
      - ./docker_pgadmin_servers.json:/pgadmin4/servers.json
    ports:
      - "25433:80"
    entrypoint:
      - "/bin/sh"
      - "-c"
      - "/bin/echo 'postgres:5432:*:postgres:password' > /tmp/pgpassfile && chmod 600 /tmp/pgpassfile && /entrypoint.sh"
    restart: unless-stopped

