server:
  port: 8080

central_inventory:
  url: "http://localhost:8081"

spring:
  application:
    name: "store-inventory"
  datasource:
    url: "jdbc:postgresql://127.0.0.1:25432/store_inventory"
    username: postgres
    password: password
  jpa:
    open-in-view: false

management:
  metrics:
    export:
      wavefront:
        api-token: "1be44ad0-ac4b-45fe-8f1e-a736e02273be"
        uri: "https://wavefront.surf"
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
